spring:
  application:
    name: customer-api
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}
    username: postgres
    password: postgres
    name: customerdb

runner:
  num-customers: 10

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

#logging:
#  level:
#    org.springframework.data.r2dbc: DEBUG

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
