spring:
  application:
    name: order-api
  data:
    cassandra:
      keyspace-name: mycompany
      contact-points: ${CASSANDRA_HOST:localhost}
      local-datacenter: datacenter1
      port: ${CASSANDRA_PORT:9042}
      schema-action: CREATE_IF_NOT_EXISTS

product-api:
  url: http://localhost:9080/api/products

customer-api:
  url: http://localhost:9081/api/customers

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
