spring:
  application:
    name: clint-shell
  main:
    web-application-type: none

product-api:
  url: http://localhost:9080/api/products

customer-api:
  url: http://localhost:9081/api/customers

order-api:
  url: http://localhost:9082/api/orders

logging:
  level:
    root: error
